# Giai đoạn 1: Build code
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /app

# Copy các file dự án và restore (tách riêng để tận dụng cache của Docker)
COPY *.sln ./
COPY *.csproj ./
RUN dotnet restore

# Copy toàn bộ code và build
COPY . ./
RUN dotnet publish -c Release -o out

# Giai đoạn 2: Chạy code
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build-env /app/out .

# Cổng mặc định của .NET 8 là 8080 (hoặc bạn có thể đổi)
EXPOSE 8080
ENTRYPOINT ["dotnet", "YourProjectName.dll"]