# Giai đoạn 1: Build code
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
WORKDIR /src

# Copy project file trước để tận dụng cache restore
COPY WebBanHang.csproj ./
RUN dotnet restore ./WebBanHang.csproj

# Copy toàn bộ source và publish
COPY . ./
RUN dotnet publish ./WebBanHang.csproj -c Release -o /app/publish /p:UseAppHost=false

# Giai đoạn 2: Chạy code
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build-env /app/publish .

EXPOSE 8080
ENTRYPOINT ["dotnet", "WebBanHang.dll"]