<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AuraMart.Ordering.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ordering.Application\Ordering.Application.csproj" />
    <ProjectReference Include="..\Ordering.Domain\Ordering.Domain.csproj" />
    <ProjectReference Include="..\Ordering.Contracts\Ordering.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\VanFucVN.Core.Persistence\VanFucVN.Core.Persistence.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\VanFucVN.Core.Messaging\VanFucVN.Core.Messaging.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\VanFucVN.Core.Common\VanFucVN.Core.Common.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\AuraMart.Shared\AuraMart.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="RabbitMQ.Client" Version="7.*" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>
</Project>
